knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google:
            # must be "google" - it activates that type!
            type: google
            # add and configure client_id and client_secret in the env file
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_google_check
            redirect_params: {}
            # optional: if you want to use the "hosted_domain" parameter
            # hosted_domain: 'example.com'
